import { Resend } from "resend";
import { buildInvoiceEmailTemplate } from "./invoiceEmail.template";
import Integration from "@/models/Integration";

/**
 * Previously always used the platform-global RESEND_API_KEY/RESEND_FROM
 * env vars, ignoring the per-business Integration(provider: EMAIL) config
 * the admin Integrations UI already lets each business configure. Now
 * looks up that business's own Resend credentials first (set via the
 * Email tab in /admin/integrations, emailProvider: 'RESEND'), and only
 * falls back to the global env vars if the business hasn't configured its
 * own key yet — so nothing breaks for businesses that haven't set this up.
 */
async function resolveResendCreds(businessId?: string): Promise<{ apiKey: string; from: string }> {
  if (businessId) {
    try {
      const integration = await Integration.findOne({
        businessId,
        provider: "EMAIL",
        isActive: true,
      }).lean();
      const cfg = (integration as any)?.config;
      if (cfg?.provider === "RESEND" && cfg?.resendApiKey) {
        return {
          apiKey: cfg.resendApiKey,
          from: cfg.resendFromEmail || cfg.fromEmail || process.env.RESEND_FROM || "",
        };
      }
    } catch (err) {
      console.error("EMAIL: failed to load business Resend config, falling back to global", err);
    }
  }
  return {
    apiKey: process.env.RESEND_API_KEY || "",
    from: process.env.RESEND_FROM || "",
  };
}

/**
 * Password-reset link email. Kept deliberately minimal (no invoice-style
 * template dependency) -- resetUrl is single-use/time-boxed, generated by
 * api/auth/reset-password/request/route.ts.
 */
export async function sendPasswordResetEmail({
  to,
  resetUrl,
  businessId,
}: {
  to: string;
  resetUrl: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: "Reset your password",
      html: `
        <p>We received a request to reset your password.</p>
        <p><a href="${resetUrl}">Click here to reset your password</a>. This link expires in 30 minutes.</p>
        <p>If you didn't request this, you can safely ignore this email.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND PASSWORD RESET EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Newsletter subscription welcome email -- best-effort, non-fatal (see caller). */
export async function sendNewsletterWelcomeEmail({
  to,
  businessId,
}: {
  to: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: "You're subscribed!",
      html: `<p>Thanks for subscribing -- we'll keep you posted on new products and offers.</p>`,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND NEWSLETTER EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Agreement e-signature OTP email. The OTP itself must never be returned
 * in an API response -- see api/agreements/[id]/otp/route.ts's fix comment. */
export async function sendAgreementOtpEmail({
  to,
  partyName,
  agreementTitle,
  otp,
  businessId,
}: {
  to: string;
  partyName: string;
  agreementTitle: string;
  otp: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: `Your OTP for signing "${agreementTitle}"`,
      html: `
        <p>Dear ${partyName},</p>
        <p>Your OTP to sign the agreement "${agreementTitle}" is: <b>${otp}</b></p>
        <p>This OTP is valid for 30 minutes.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND AGREEMENT OTP EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

export async function sendInvoiceEmail({
  to,
  customerName,
  invoiceNumber,
  pdfUrl,
  grandTotal,
  orderId,
  businessId,
}: any) {
  try {

    console.log("RESEND EMAIL START", {
      to,
      invoiceNumber,
      orderId,
      businessId,
    });

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const html = buildInvoiceEmailTemplate({
      customerName,
      invoiceNumber,
      pdfUrl,
      grandTotal,
      orderId,
    });

    const result = await resend.emails.send({
      from,
      to,
      subject: `Invoice ${invoiceNumber} | AN Group`,
      html,
    });

    console.log(
      "RESEND SUCCESS",
      JSON.stringify(result, null, 2)
    );

    return {
      success: true,
      result,
    };

  } catch (err: any) {

    console.error(
      "RESEND ERROR",
      err
    );

    return {
      success: false,
      error:
        err?.message ||
        "Unknown email error",
    };
  }
}
