import { Resend } from "resend";
import { buildInvoiceEmailTemplate } from "./invoiceEmail.template";
import Integration from "@/models/Integration";

/**
 * Previously always used the platform-global RESEND_API_KEY/RESEND_FROM
 * env vars, ignoring the per-business Integration(provider: EMAIL) config
 * the admin Integrations UI already lets each business configure. Now
 * looks up that business's own Resend credentials first (set via the
 * Email tab in /admin/integrations, emailProvider: 'RESEND'), and only
 * falls back to the global env vars if the business hasn't configured its
 * own key yet — so nothing breaks for businesses that haven't set this up.
 */
async function resolveResendCreds(businessId?: string): Promise<{ apiKey: string; from: string }> {
  if (businessId) {
    try {
      const integration = await Integration.findOne({
        businessId,
        provider: "EMAIL",
        isActive: true,
      }).lean();
      const cfg = (integration as any)?.config;
      if (cfg?.provider === "RESEND" && cfg?.resendApiKey) {
        return {
          apiKey: cfg.resendApiKey,
          from: cfg.resendFromEmail || cfg.fromEmail || process.env.RESEND_FROM || "",
        };
      }
    } catch (err) {
      console.error("EMAIL: failed to load business Resend config, falling back to global", err);
    }
  }
  return {
    apiKey: process.env.RESEND_API_KEY || "",
    from: process.env.RESEND_FROM || "",
  };
}

/**
 * Password-reset link email. Kept deliberately minimal (no invoice-style
 * template dependency) -- resetUrl is single-use/time-boxed, generated by
 * api/auth/reset-password/request/route.ts.
 */
export async function sendPasswordResetEmail({
  to,
  resetUrl,
  businessId,
}: {
  to: string;
  resetUrl: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: "Reset your password",
      html: `
        <p>We received a request to reset your password.</p>
        <p><a href="${resetUrl}">Click here to reset your password</a>. This link expires in 30 minutes.</p>
        <p>If you didn't request this, you can safely ignore this email.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND PASSWORD RESET EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/**
 * Generic email-verification OTP -- used by any public/unauthenticated flow
 * that needs to confirm a real email address before accepting a submission
 * (currently: the public appointment-request page). Deliberately separate
 * from sendAgreementOtpEmail, which is purpose-built for signing an
 * agreement and carries agreement-specific copy/context.
 */
export async function sendVerificationOtpEmail({
  to,
  otp,
  purpose,
  businessId,
}: {
  to: string;
  otp: string;
  purpose: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: `Your verification code: ${otp}`,
      html: `
        <p>Your verification code for ${purpose} is:</p>
        <p style="font-size:28px;font-weight:700;letter-spacing:4px;">${otp}</p>
        <p>This code is valid for 10 minutes. If you didn't request this, you can ignore this email.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND VERIFICATION OTP EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Newsletter subscription welcome email -- best-effort, non-fatal (see caller). */
export async function sendNewsletterWelcomeEmail({
  to,
  businessId,
}: {
  to: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: "You're subscribed!",
      html: `<p>Thanks for subscribing -- we'll keep you posted on new products and offers.</p>`,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND NEWSLETTER EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Agreement e-signature OTP email. The OTP itself must never be returned
 * in an API response -- see api/agreements/[id]/otp/route.ts's fix comment. */
export async function sendAgreementOtpEmail({
  to,
  partyName,
  agreementTitle,
  otp,
  signingLink,
  businessId,
}: {
  to: string;
  partyName: string;
  agreementTitle: string;
  otp: string;
  signingLink?: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: `Action required: sign "${agreementTitle}"`,
      html: `
        <p>Dear ${partyName},</p>
        <p>You have been requested to sign the agreement "${agreementTitle}".</p>
        ${signingLink ? `<p><a href="${signingLink}">Click here to review and sign</a></p>` : ""}
        <p>Your OTP to verify your identity and sign is: <b>${otp}</b></p>
        <p>This OTP is valid for 30 minutes.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND AGREEMENT OTP EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Registration welcome email -- best-effort, non-fatal (see callers). */
export async function sendWelcomeEmail({
  to,
  name,
  businessId,
}: {
  to: string;
  name: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: "Welcome to AN Group",
      html: `
        <p>Hi ${name},</p>
        <p>Your account has been created successfully. You can now sign in and get started.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND WELCOME EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Sent when an admin/vendor creates a login for someone else with an
 * admin-assigned temporary password -- pairs with mustChangePassword: true
 * set on the User doc, so the recipient is prompted to change it on first
 * login. Best-effort, non-fatal (see callers). */
export async function sendAccountCredentialsEmail({
  to,
  name,
  loginUrl,
  tempPassword,
  businessId,
}: {
  to: string;
  name: string;
  loginUrl?: string;
  tempPassword?: string;
  businessId?: string;
}) {
  try {
    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: "Your AN Group account is ready",
      html: `
        <p>Hi ${name},</p>
        <p>An account has been created for you on AN Group.</p>
        <p>Login email: <b>${to}</b></p>
        ${tempPassword ? `<p>Temporary password: <b>${tempPassword}</b></p>` : ""}
        ${loginUrl ? `<p><a href="${loginUrl}">Click here to sign in</a>.</p>` : ""}
        <p>You'll be asked to set a new password the first time you sign in.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND ACCOUNT CREDENTIALS EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

export async function sendInvoiceEmail({
  to,
  customerName,
  invoiceNumber,
  pdfUrl,
  grandTotal,
  orderId,
  businessId,
}: any) {
  try {

    console.log("RESEND EMAIL START", {
      to,
      invoiceNumber,
      orderId,
      businessId,
    });

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const html = buildInvoiceEmailTemplate({
      customerName,
      invoiceNumber,
      pdfUrl,
      grandTotal,
      orderId,
    });

    const result = await resend.emails.send({
      from,
      to,
      subject: `Invoice ${invoiceNumber} | AN Group`,
      html,
    });

    console.log(
      "RESEND SUCCESS",
      JSON.stringify(result, null, 2)
    );

    return {
      success: true,
      result,
    };

  } catch (err: any) {

    console.error(
      "RESEND ERROR",
      err
    );

    return {
      success: false,
      error:
        err?.message ||
        "Unknown email error",
    };
  }
}
