import type { AnuKnowledgeEntry } from "./types";
import { listModulesForBusiness } from "@/core/module-registry/moduleDefinition.service";
import { listPendingFilings } from "@/core/gst/gstFilingService";

/**
 * Static platform knowledge ANu is grounded in, regardless of business.
 * This is deliberately hand-maintained prose (not auto-scraped code) so it
 * stays accurate and readable — update this list whenever a genuinely new
 * platform-level capability ships (a new core/ system, a new admin
 * workflow), not for every small change.
 */
const STATIC_KNOWLEDGE: AnuKnowledgeEntry[] = [
  {
    topic: "Modules",
    summary:
      "Every business object type (Orders, Inventory, Vendors, custom types an admin invents, etc.) is a 'module'. Admins can create entirely new modules with their own custom fields from Settings > Modules, no code changes needed — this is called the module registry.",
  },
  {
    topic: "Access & Permissions",
    summary:
      "Access to every module (and each action within it — view/create/edit/delete/export/approve/manage_settings) is controlled by Roles. An admin grants a role a set of permission checkboxes on the Access Matrix screen (Admin > Roles), then assigns that role to a user. A module only appears in a user's sidebar if their role grants that module's 'view' permission.",
  },
  {
    topic: "Numbering",
    summary:
      "Document numbers (invoices, purchase orders, GRNs, etc.) are generated by one shared numbering engine, configurable per business and per document type in Settings > Document Numbers (prefix, financial-year segment, sequence length, etc.).",
  },
  {
    topic: "Integrations",
    summary:
      "Telegram, WhatsApp, Slack, and email notifications, plus Shiprocket (shipping) and Razorpay (payments), are configured per business in Settings > Integrations.",
  },
  {
    topic: "Businesses",
    summary:
      "This is a multi-tenant platform — one login can belong to multiple businesses. Users switch their active business from the business switcher; every module/record is scoped to the active business.",
  },
  {
    topic: "GST Filing",
    summary:
      "Sales invoices can be pushed directly to the GST portal from Admin > GST Filing. An admin first configures the business's GSTIN and portal provider in Settings > GST Filing, then queues an invoice for a return period (GSTR1 / GSTR3B / IFF) and submits it. Each filing tracks a status: PENDING (queued, not yet sent), SUBMITTED (sent, awaiting portal decision), ACCEPTED, REJECTED, or FAILED (our own push attempt failed before reaching the portal). You can help users understand what's pending, why something failed or was rejected (see the filing's rejectionReason), and what to do next — but you cannot submit a filing yourself; that always requires an admin action in the UI.",
  },
];

/**
 * Build ANu's grounding context for one query: static platform knowledge +
 * a live list of this business's actual enabled modules (so ANu never tells
 * a user about a module they don't have, or misses one they do).
 */
export async function buildAnuContext(businessId: string): Promise<string> {
  const modules = await listModulesForBusiness(businessId).catch(() => []);

  const moduleList = modules
    .map((m: any) => `- ${m.label} (key: ${m.key}, route: ${m.route})`)
    .join("\n");

  const staticSection = STATIC_KNOWLEDGE.map(
    (k) => `## ${k.topic}\n${k.summary}`
  ).join("\n\n");

  // Live GST-pendings snapshot, same "don't hallucinate — inject the real
  // live data" principle as the enabled-modules list below. Only fetched if
  // the business actually has the gst module enabled, to avoid an
  // unnecessary query for businesses that never touch GST filing.
  const gstEnabled = modules.some((m: any) => m.key === "gst");
  let gstSection = "";
  if (gstEnabled) {
    const pending = await listPendingFilings(businessId).catch(() => []);
    if (pending.length > 0) {
      const lines = pending
        .slice(0, 20)
        .map(
          (f: any) =>
            `- Invoice ${f.invoiceNumber}, ${f.returnType} ${f.period}: ${f.status}${f.rejectionReason ? ` (${f.rejectionReason})` : ""}`
        )
        .join("\n");
      gstSection = [
        "",
        "## Currently pending GST filings for this business",
        lines,
        pending.length > 20 ? `...and ${pending.length - 20} more.` : "",
      ].join("\n");
    }
  }

  return [
    "You are ANu, the in-house AI assistant for this ERP platform. You help users understand and use the system — answer 'how do I...' and 'what can I do...' questions grounded ONLY in the information below. If asked about something not covered here, say you're not sure rather than guessing at a feature that may not exist.",
    "",
    staticSection,
    "",
    "## Modules currently enabled for this business",
    moduleList || "(none enabled yet)",
    gstSection,
  ].join("\n");
}
