/**
 * Canonical document-numbering type list.
 *
 * CONSOLIDATION CONTEXT (see PROGRESS.md's "Known duplicates to consolidate"
 * — this was Phase 1 blocking item #1): the original repo had SIX separate
 * number-generating implementations (services/numbering.service.ts,
 * services/documentEngine.ts, services/invoice.service.ts,
 * services/sales.service.ts, services/purchaseOrder.service.ts,
 * lib/invoice/generateInvoiceNumber.ts) and FOUR separate counter-storage
 * models (Sequence, Counter, DocumentCounter, InvoiceSequence), plus THREE
 * different getFinancialYear() implementations that didn't even agree on
 * output format (one returned "2026-27", another "2627"). Two of the six
 * generators (sales.service.ts's `"INV-" + Date.now()` and
 * purchaseOrder.service.ts's `"PO-" + Date.now()`) and one more
 * (invoice.service.ts, via a `countDocuments()`-based sequence) were
 * actively unsafe: Date.now()-based numbers can collide on concurrent
 * requests within the same millisecond, and countDocuments()-based
 * sequences are a classic race condition (two concurrent creates can both
 * read count=N and both generate number N+1) AND silently reuse numbers
 * after any document is deleted. Neither respected the admin-configurable
 * prefix/format that DocumentNumberConfig (and its admin UI at
 * Settings > Document Numbers) already existed to control.
 *
 * This file/module replaces ALL of the above with exactly one engine
 * (numberingService.ts) backed by exactly one atomic counter collection
 * (NumberSequence.model.ts) reading its prefix/format from the existing
 * DocumentNumberConfig model — so the admin UI actually controls every
 * document type's numbering, not just invoices.
 *
 * DOCUMENT_TYPES here is the UNION of DocumentNumberConfig.DOCUMENT_TYPES
 * (the admin-configurable set, already covers most GST/finance documents)
 * and the extra types the old Sequence model's enum had that
 * DocumentNumberConfig didn't (PRODUCT, PRODUCT_VARIANT, VENDOR_PRODUCT,
 * STOCK_ADJUSTMENT, STOCK_TRANSFER, PRODUCTION_ORDER, BATCH,
 * CUSTOMER_ORDER, RECEIPT) — nothing from either prior list is dropped.
 */

export const DOCUMENT_TYPES = [
  // From DocumentNumberConfig (already admin-configurable via existing UI)
  "INVOICE",
  "SALES_ORDER",
  "PURCHASE_ORDER",
  "GRN",
  "CREDIT_NOTE",
  "DEBIT_NOTE",
  "QUOTATION",
  "DELIVERY_CHALLAN",
  "PAYMENT_RECEIPT",
  "PRODUCTION_ORDER",
  // From the old Sequence model's enum (not previously admin-configurable —
  // now folded into the same config + UI)
  "PRODUCT",
  "PRODUCT_VARIANT",
  "VENDOR_PRODUCT",
  "STOCK_ADJUSTMENT",
  "STOCK_TRANSFER",
  "BATCH",
  "CUSTOMER_ORDER",
  "RECEIPT",
  // Discovered during the live-callsite sweep (a 10th duplicate generator
  // was found in app/api/agreements/create/route.ts, globally-scoped with
  // no businessId filter at all) — added here so agreement numbering is
  // admin-configurable like everything else.
  "AGREEMENT",
  // Discovered during the same sweep: VENDOR and EMPLOYEE IDs were each
  // generated by 3+ independently-drifted implementations across different
  // routes (VendorProfile.vendorId used "VND-" with 4-digit padding in two
  // routes and "VEN-" with 3-digit padding in a third; EmployeeProfile
  // followed a similar pattern) — all via countDocuments(), which is
  // globally-scoped (not per-business) AND race-prone. Folded into one
  // configurable type each so there's exactly one format, admin-editable,
  // going forward.
  "VENDOR",
  "EMPLOYEE",
  // Discovered later, from a real user report: creating a new Business
  // still generated its businessCode via `BUS-${Date.now()}` in
  // businessBootstrap.service.ts — never migrated during the original
  // consolidation sweep above, so it was the one entity code left
  // completely outside admin control despite this whole system existing
  // specifically to fix that class of bug.
  "BUSINESS",
  // A vendor signup request needs a tracking number the moment it's
  // submitted, before any business (and therefore before VENDOR's
  // businessId-aware numbering config) has been assigned — see
  // api/vendors/apply/route.ts and VendorProfile.requestNumber.
  "VENDOR_REQUEST",
  // CRM call-lifecycle module (call entry -> job sheet -> closure — see
  // models/CrmCall.ts and models/CrmJobSheet.ts). CALL is the human-facing
  // reference on a CrmCall record; JOB_SHEET is the reference on a
  // CrmJobSheet created when a call is converted into actual work. Both are
  // admin-configurable per business through the same Settings > Document
  // Numbers UI as every other document type here, rather than inventing a
  // separate ad-hoc numbering scheme for CRM.
  "CALL",
  "JOB_SHEET",
  // Warehouse/service-center codes were previously manually typed in the
  // creation form with no numbering at all — added so they're generated
  // atomically and admin-configurable like every other document type here.
  "WAREHOUSE",
  "SERVICE_CENTER",
  // Store Front facility codes — same pattern as WAREHOUSE/SERVICE_CENTER
  // above, generated when a vendor's enableStoreFront toggle is switched on
  // (see VendorProfile.storeFrontId / /api/vendors/[id]'s PUT handler).
  "STORE_FRONT",
  // Vendor-created materials (added inline from the vendor product wizard's
  // BOM step, see api/vendor/materials/route.ts) -- the raw sequence from
  // this type is used to build "<vendorCode>-MAT-00001", not this type's
  // own INV-style formatted value, but it still needs a registered
  // DocumentType to get an atomic, per-vendor-scoped counter the same way
  // every other numbered entity in this file does.
  "MATERIAL",
  // CRM job-sheet closure (api/crm/jobsheets/[id]/close) generates a
  // SalesInvoice per job -- per explicit requirement, a GST-bearing
  // invoice and a non-GST invoice must NOT share one running series (a
  // business needs its GST-taxable invoice numbers to be their own
  // consecutive sequence for filing purposes, separate from zero-GST/
  // exempt bills). Reuses "INVOICE" for the GST case; this type is only
  // for the non-GST case.
  "NON_GST_INVOICE",
  // Same job-sheet-closure invoice as above, but for the case where the
  // customer entered a company name (a B2B customer) -- gets its own
  // running series, separate from the walk-in/individual (B2C) series,
  // per explicit requirement.
  "B2B_INVOICE",
  // The one document type from models/SalesDocument.ts's set that wasn't
  // already in this list (QUOTATION/DELIVERY_CHALLAN/CREDIT_NOTE/DEBIT_NOTE
  // all pre-existed here already, just never had a page/print until now).
  "PROFORMA_INVOICE",
  // Per-role human-facing serial (Role.roleNumber), format "{businessCode}-
  // {seq}" via a seeded global DocumentNumberConfig template -- see
  // scripts/seedRoleNumberConfig.ts.
  "ROLE",
] as const;

export type DocumentType = (typeof DOCUMENT_TYPES)[number];

/**
 * Sensible built-in default prefix per document type, used the first time a
 * business generates a number for a type it hasn't explicitly configured
 * yet (DocumentNumberConfig row doesn't exist) — mirrors the defaults the
 * existing /api/admin/document-numbers GET handler already shows in the UI
 * before a business saves its own, plus defaults for the newly-folded-in
 * types that UI didn't cover yet.
 */
export const DEFAULT_PREFIXES: Record<DocumentType, string> = {
  INVOICE: "INV",
  SALES_ORDER: "SO",
  PURCHASE_ORDER: "PO",
  GRN: "GRN",
  CREDIT_NOTE: "CN",
  DEBIT_NOTE: "DN",
  QUOTATION: "QT",
  DELIVERY_CHALLAN: "DC",
  PAYMENT_RECEIPT: "PR",
  PRODUCTION_ORDER: "MFG",
  PRODUCT: "PRD",
  PRODUCT_VARIANT: "VAR",
  VENDOR_PRODUCT: "VPRD",
  STOCK_ADJUSTMENT: "SA",
  STOCK_TRANSFER: "TRF",
  BATCH: "BAT",
  CUSTOMER_ORDER: "ORD",
  RECEIPT: "RCT",
  AGREEMENT: "AGR",
  VENDOR: "VND",
  EMPLOYEE: "EMP",
  BUSINESS: "BUS",
  VENDOR_REQUEST: "VREQ",
  CALL: "CALL",
  JOB_SHEET: "JOB",
  WAREHOUSE: "WH",
  SERVICE_CENTER: "SC",
  STORE_FRONT: "SF",
  MATERIAL: "MAT",
  NON_GST_INVOICE: "BILL",
  B2B_INVOICE: "BINV",
  PROFORMA_INVOICE: "PI",
  ROLE: "ROLE",
};

export interface GeneratedNumber {
  /** The final formatted document number, e.g. "INV-2025-26-0001". */
  value: string;
  /** The raw numeric sequence used, before formatting — for audit/debug. */
  sequence: number;
}
