export const ACCESS = {
  UNIT_VIEW: "UNIT_VIEW",
  UNIT_CREATE: "UNIT_CREATE",
  UNIT_EDIT: "UNIT_EDIT",
  UNIT_DELETE: "UNIT_DELETE",

  VENDOR_VIEW: "VENDOR_VIEW",
  VENDOR_CREATE: "VENDOR_CREATE",
  VENDOR_EDIT: "VENDOR_EDIT",
  VENDOR_DELETE: "VENDOR_DELETE",

  BRAND_VIEW: "BRAND_VIEW",
  BRAND_CREATE: "BRAND_CREATE",
  BRAND_EDIT: "BRAND_EDIT",
  BRAND_DELETE: "BRAND_DELETE",

  MATERIAL_VIEW: "MATERIAL_VIEW",
  MATERIAL_CREATE: "MATERIAL_CREATE",
  MATERIAL_EDIT: "MATERIAL_EDIT",
  MATERIAL_DELETE: "MATERIAL_DELETE",

  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_EDIT: "PRODUCT_EDIT",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  BOM_VIEW: "BOM_VIEW",
  BOM_CREATE: "BOM_CREATE",
  BOM_EDIT: "BOM_EDIT",
  BOM_DELETE: "BOM_DELETE",
  BOM_APPROVE: "BOM_APPROVE",
} as const;
