/**
 * Fixed electronics "Device Type" taxonomy, used consistently across Brand
 * (category), FaultCode/SymptomCode (deviceCategory — the new top wrapping
 * level above the existing free-text `category`, which represents the
 * component, e.g. "Screen"/"Battery"), and VendorProfile.productCategories
 * (which categories a vendor services). Same const-array-plus-type pattern
 * as businessScope.ts.
 *
 * Covers 42 categories spanning every electronics/appliance category
 * commonly launched/sold in the Indian consumer electronics market.
 */
export const DEVICE_CATEGORIES = [
  "MOBILE",
  "FEATURE_PHONE",
  "TABLET",
  "LAPTOP",
  "DESKTOP",
  "MONITOR",
  "COMPUTER_ACCESSORY",
  "PRINTER_SCANNER",
  "TELEVISION",
  "PROJECTOR",
  "SET_TOP_BOX",
  "SOUNDBAR",
  "SPEAKER",
  "HEADPHONE_EARBUD",
  "SMARTWATCH",
  "FITNESS_BAND",
  "CAMERA",
  "CAMCORDER",
  "DRONE",
  "GAMING_CONSOLE",
  "ROUTER_NETWORKING",
  "POWER_BANK",
  "UPS_INVERTER",
  "CCTV_SECURITY",
  "SMART_HOME",
  "REFRIGERATOR",
  "WASHING_MACHINE",
  "AIR_CONDITIONER",
  "MICROWAVE",
  "OTG_OVEN",
  "DISHWASHER",
  "WATER_PURIFIER",
  "AIR_PURIFIER",
  "VACUUM_CLEANER",
  "CHIMNEY",
  "INDUCTION_COOKTOP",
  "MIXER_GRINDER",
  "WATER_HEATER",
  "IRON",
  "PERSONAL_GROOMING",
  "FAN",
  "AIR_COOLER",
  "CALCULATOR",
  "VR_HEADSET",
  "E_READER",
] as const;

export type DeviceCategory = (typeof DEVICE_CATEGORIES)[number];

export const DEVICE_CATEGORY_LABELS: Record<DeviceCategory, string> = {
  MOBILE: "Mobile Phones",
  FEATURE_PHONE: "Feature Phones",
  TABLET: "Tablets",
  LAPTOP: "Laptops",
  DESKTOP: "Desktop / PC",
  MONITOR: "Monitors",
  COMPUTER_ACCESSORY: "Computer Accessories",
  PRINTER_SCANNER: "Printers & Scanners",
  TELEVISION: "Television",
  PROJECTOR: "Projectors",
  SET_TOP_BOX: "Set-Top Box",
  SOUNDBAR: "Soundbars",
  SPEAKER: "Speakers",
  HEADPHONE_EARBUD: "Headphones & Earbuds",
  SMARTWATCH: "Smartwatches",
  FITNESS_BAND: "Fitness Bands",
  CAMERA: "Cameras",
  CAMCORDER: "Camcorders",
  DRONE: "Drones",
  GAMING_CONSOLE: "Gaming Consoles",
  ROUTER_NETWORKING: "Routers & Networking",
  POWER_BANK: "Power Banks",
  UPS_INVERTER: "UPS & Inverters",
  CCTV_SECURITY: "CCTV & Security",
  SMART_HOME: "Smart Home Devices",
  REFRIGERATOR: "Refrigerator",
  WASHING_MACHINE: "Washing Machine",
  AIR_CONDITIONER: "Air Conditioner",
  MICROWAVE: "Microwave",
  OTG_OVEN: "OTG / Oven Toaster Griller",
  DISHWASHER: "Dishwasher",
  WATER_PURIFIER: "Water Purifier",
  AIR_PURIFIER: "Air Purifier",
  VACUUM_CLEANER: "Vacuum Cleaner",
  CHIMNEY: "Kitchen Chimney",
  INDUCTION_COOKTOP: "Induction Cooktop",
  MIXER_GRINDER: "Mixer Grinder",
  WATER_HEATER: "Water Heater / Geyser",
  IRON: "Iron",
  PERSONAL_GROOMING: "Personal Grooming (Trimmer/Dryer)",
  FAN: "Fans",
  AIR_COOLER: "Air Cooler",
  CALCULATOR: "Calculators",
  VR_HEADSET: "VR Headsets",
  E_READER: "E-Readers",
};
